#!/usr/bin/env python3
"""
simulator.py - Simula l'invio di dati da un dispositivo ESP32 a un server Raspberry Pi/App Flask.

Usage:
    python3 simulator.py

Configurazione (modificare direttamente nel file se necessario):
    HOST: 127.0.0.1
    PORT: 8000
    DEVICE_ID: autogenerated (Esp_Simulator_<6hex>)

Features:
- Invio dati veloci (luminosità + audio_raw) ogni 225 ms
- Invio dati lenti (temperatura + umidità) ogni 1 s
- Valori sensori con trend e cicli giornalieri
- Retry esponenziale su timeout di connessione
- Logging dettagliato
"""
import threading
import time
import random
import math
import socket
import uuid
import requests
import logging

# Configurazione server
HOST = "127.0.0.1"  # Modifica se il server è su altro host
PORT = 8000         # Modifica se il server usa porta diversa

# Simulation intervals
FAST_INTERVAL = 0.225  # secondi: luminosità + audio
SLOW_INTERVAL = 1.0    # secondi: temperatura + umidità
NUM_AUDIO_SAMPLES = 100

# Retry settings
MAX_RETRIES = 3
BACKOFF_FACTOR = 2
INITIAL_TIMEOUT = 5

# Trend variables
temp_trend = humidity_trend = light_trend = audio_trend = 0.0
BASE_TEMP = 22.0
BASE_HUM = 45.0

# Logging
logging.basicConfig(
    format="%(asctime)s %(levelname)s: %(message)s",
    level=logging.INFO,
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger()


def get_local_ip():
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.connect(("8.8.8.8", 80))
            return s.getsockname()[0]
    except:
        return "127.0.0.1"


def register_device(device_id, mac):
    url = f"http://{HOST}:{PORT}/api/device_register"
    payload = {
        "device_id": device_id,
        "mac_address": mac,
        "ip_address": get_local_ip(),
        "rssi": random.randint(-70, -30)
    }
    try:
        resp = requests.post(url, json=payload, timeout=INITIAL_TIMEOUT)
        if resp.status_code == 200:
            logger.info(f"Dispositivo registrato: {payload}")
        else:
            logger.warning(f"Registrazione fallita ({resp.status_code})")
    except requests.exceptions.RequestException as e:
        logger.error(f"Errore registrazione: {e}")


def generate_realistic_temperature():
    global temp_trend
    hour = (time.time() / 3600) % 24
    daily = 3 * math.sin((hour - 6) * math.pi / 12)
    temp_trend += random.uniform(-0.05, 0.05)
    temp_trend = max(-2.0, min(2.0, temp_trend))
    noise = random.uniform(-0.3, 0.3)
    return round(BASE_TEMP + daily + temp_trend + noise, 1)


def generate_realistic_humidity():
    global humidity_trend, temp_trend
    humidity_trend += random.uniform(-0.1, 0.1)
    humidity_trend = max(-5.0, min(5.0, humidity_trend))
    noise = random.uniform(-2.0, 2.0)
    h = BASE_HUM - (temp_trend * 0.5) + humidity_trend + noise
    return round(max(20.0, min(80.0, h)), 1)


def generate_realistic_light():
    global light_trend
    hour = (time.time() / 3600) % 24
    if 6 <= hour <= 18:
        base = 800 + 400 * math.sin((hour - 6) * math.pi / 12)
    else:
        base = 50 + random.uniform(0, 20)
    light_trend += random.uniform(-5, 5)
    light_trend = max(-100, min(100, light_trend))
    noise = random.uniform(-50, 50)
    return max(0, min(4095, int(base + light_trend + noise)))


def generate_audio_samples():
    global audio_trend
    samples = []
    for _ in range(NUM_AUDIO_SAMPLES):
        base = random.uniform(50, 150)
        if random.random() < 0.01:
            base += random.uniform(500, 1000)
        audio_trend += random.uniform(-2, 2)
        audio_trend = max(-50, min(50, audio_trend))
        samples.append(int(max(0, min(2047, base + audio_trend))))
    return samples


def post_data(payload):
    url = f"http://{HOST}:{PORT}/api/data"
    timeout = INITIAL_TIMEOUT
    for attempt in range(1, MAX_RETRIES+1):
        try:
            resp = requests.post(url, json=payload, timeout=timeout)
            if resp.status_code == 200:
                logger.debug("Dati inviati con successo")
                return True
            else:
                logger.warning(f"Errore server ({resp.status_code})")
                return False
        except requests.exceptions.ConnectTimeout:
            logger.error(f"ConnectTimeout tentativo {attempt}")
        except requests.exceptions.RequestException as e:
            logger.error(f"Errore invio: {e}")
            break
        timeout *= BACKOFF_FACTOR
        time.sleep(timeout)
    logger.error("Invio dati fallito dopo retry")
    return False


def fast_loop(device_id):
    while True:
        payload = {
            "device_id": device_id,
            "l": generate_realistic_light(),
            "audio_raw": generate_audio_samples()
        }
        post_data(payload)
        time.sleep(FAST_INTERVAL)


def slow_loop(device_id):
    while True:
        payload = {
            "device_id": device_id,
            "t": generate_realistic_temperature(),
            "h": generate_realistic_humidity()
        }
        post_data(payload)
        time.sleep(SLOW_INTERVAL)


def main():
    # Genera ID e MAC
    device_id = f"Esp_Simulator"
    mac = ":".join(f"{random.randint(0,255):02x}" for _ in range(6))

    logger.info(f"Simulator avviato: {device_id} -> {HOST}:{PORT}")
    register_device(device_id, mac)

    threading.Thread(target=fast_loop, args=(device_id,), daemon=True).start()
    threading.Thread(target=slow_loop, args=(device_id,), daemon=True).start()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        logger.info("Simulator interrotto")


if __name__ == "__main__":
    main()
